spring:
  datasource:
    url: jdbc:mysql:///dubbo_student
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: stu_service_student
    registry:
      address: zookeeper://192.168.67.128:2181
server:
  port: 6666
